language: go
go:
  - '1.10.2'
before_script:
  - sudo apt-get -qq update
  - sudo apt-get install -y sqlite3
  - go get github.com/mattn/go-sqlite3
  - go get github.com/jinzhu/gorm
  - go get github.com/Unknwon/com
script:
  - openssl aes-256-cbc -K $encrypted_6aeb6f62faaa_key -iv $encrypted_6aeb6f62faaa_iv -in deploy-key.enc -out deploy-key -d
  - chmod 600 deploy-key
  - eval `ssh-agent -s`
  - ssh-add deploy-key
  - git config user.name "Tosone"
  - git config user.email "i@tosiney.com"
  - git remote add gh-pages git@github.com:tosone/ExploitDatabase.git
  - git fetch gh-pages && git fetch gh-pages gh-pages:gh-pages
  - git worktree add -B gh-pages public gh-pages
  - make all && make release
